# fly.toml app configuration file generated for foretagscenter-client on 2023-10-12T09:40:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "foretagscenter-client"
primary_region = "arn"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
